### ISSUE TITLE
Oxalis not starting with AS4 plugin

### ISSUE THREAD

**Issue by bluejudas** [difi/Oxalis-AS4#51]
Hi,

Windows
Oxalis 4.1
jdk1.8.0_25
Apache Tomcat/9.0.10

My Oxalis run fine without the AS4 plugin. 

![image](https://user-images.githubusercontent.com/59683931/72049661-ab29b100-32bf-11ea-9644-625f226db6b9.png)

But when I try to enable the plugin I get this exception.
```
SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [no.difi.oxalis.dist.war.WarServletContextListener]
 java.lang.NoClassDefFoundError: no/difi/oxalis/inbound/OxalisGuiceContextListener
```

It looks like Oxalis is starting (from the oxalis.log):

```
...
2020-01-09 08:52:26,205 INFO [no.difi.vefa.peppol.security.ModeDetector] [] Detected mode: TEST 
2020-01-09 08:52:26,236 DEBUG [org.apache.cxf.common.logging.LogUtils] [] Using org.apache.cxf.common.logging.Slf4jLogger for logging. 
2020-01-09 08:52:26,596 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] [] Inbound folder: D:\Oxalis\peppol 
```

This is my Context:

```
<?xml version="1.0" encoding="UTF-8"?>
<Context docBase="D:\Oxalis\bin\oxalis-4.1.0.war"  >
   <Resources className="org.apache.catalina.webresources.ExtractingRoot">
      <PostResources
        base="D:\Oxalis\bin\oxalis-as4-4.1.0-SNAPSHOT-dist\" 
        className="org.apache.catalina.webresources.DirResourceSet"
        webAppMount="/WEB-INF/lib"
        />  
   </Resources>
</Context>
```

I have downloaded the AS4 plugin and copied the files to my local folder:

![image](https://user-images.githubusercontent.com/59683931/72050048-81bd5500-32c0-11ea-9160-13a848bc57f2.png)

**Comment by FrodeBjerkholt** [comment]
Which release/branch of Oxalis-AS4 are you using?

**Comment by bluejudas** [comment]
I downloaded RC10 from releases.

**Comment by FrodeBjerkholt** [comment]
Can you try RC9 and see if you get the same problem ?

**Comment by bluejudas** [comment]
Same error with RC9.

**Comment by FrodeBjerkholt** [comment]
Strange. You are the first to report this problem.

**Comment by bluejudas** [comment]
I have also tried to download master and compile it myself.

**Comment by bluejudas** [comment]
When I comment out PostResources it works, but of course no AS4 support.

```
<?xml version="1.0" encoding="UTF-8"?>
<Context docBase="D:\Oxalis\bin\oxalis-4.1.0.war"  >
   <Resources className="org.apache.catalina.webresources.ExtractingRoot">
      <!--PostResources
        base="D:\Oxalis\bin\oxalis-as4-4.1.0-SNAPSHOT-dist_master\" 
        className="org.apache.catalina.webresources.DirResourceSet"
        webAppMount="/WEB-INF/lib"
        /-->  
   </Resources>
</Context>
```

**Comment by arnemorten** [comment]
Your java version is very old. Try upgrading it.

**Comment by bluejudas** [comment]
> Your java version is very old. Try upgrading it.

That should not be a problem?

https://github.com/difi/oxalis =>make sure JDK 8 is installed (the version we have tested with)

**Comment by arnemorten** [comment]
You are running u25.  Latest is u231.

**Comment by bluejudas** [comment]
u231 did not help.

```
09-Jan-2020 15:25:19.403 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             D:\Java\jdk1.8.0_231\jre
```
Still same problem.

```
09-Jan-2020 15:25:45.708 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [no.difi.oxalis.dist.war.WarServletContextListener]
 java.lang.NoClassDefFoundError: no/difi/oxalis/inbound/OxalisGuiceContextListener
```

**Comment by bluejudas** [comment]
I got this to work by putting as4 snapshot folder in common.loader in catalina.properties.

`common.loader="D:/Oxalis/bin/oxalis-as4-4.1.0-SNAPSHOT-dist_master/*.jar"`

Any suggestions on how to solve this without this "hack"?

**Comment by FrodeBjerkholt** [comment]
Not really, but I will try to reproduce the NoClassDefFoundError later today. As you probably know, the NoClassDefFoundError will come if a class was present during compile time but not available in java classpath during runtime.

**Comment by PPotappel** [comment]
Did you try to upgrade Tomcat to the latest version?

**Comment by FrodeBjerkholt** [comment]
No. I tried with tomcat-8.5.50 and that worked as expected. I have tried both downloading the dist files for RC9 and building the distribution from the sources. I will try the newest tomcat now.

**Comment by FrodeBjerkholt** [comment]
I have now tried with tomcat-9.0.30 and that also worked as expected. Maybe you should try starting the AS4 installation from scratch?

**Comment by sanderverhoeven** [comment]
I had the same problem with Tomcat 9.0.25 after upgrade to 9.0.30 everything worked as expected.

**Comment by bluejudas** [comment]
> I had the same problem with Tomcat 9.0.25 after upgrade to 9.0.30 everything worked as expected.

Yes that solved the issue for me too.
